# This is a basic workflow to help you get started with Actions

name: CI

on: [pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        os:
          - leap
          - tumbleweed
          - debian
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run:  for f in t/environ/*.sh ; do ( cd t/environ && ./${f##*/} ) && continue; echo FAIL $f; exit 1; done
        env:
          T_BASE_IMAGE: ${{ matrix.os }}
